# Generated by Django 5.2.3 on 2025-06-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecodedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_image', models.ImageField(upload_to='decoded_inputs/')),
                ('decoded_message', models.TextField(blank=True, null=True)),
                ('decoded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
